### ISSUE TITLE
COPYING and INSTALL are symbolic links

### ISSUE THREAD

**Issue by UniQP** [rdmpage/maximum-weighted-bipartite-matching#4]
The files COPYING and INSTALL are symbolic links to /usr/local/Cellar/automake/1.15/share/automake-1.15/COPYING and /usr/local/Cellar/automake/1.15/share/automake-1.15/INSTALL. Since these files do not exists on every system, you should provide a copy of the files.

**Comment by rdmpage** [comment]
I've chosen to add these to .gitignore for now.
