### ISSUE TITLE
Cannot reprodue the steps to build the project

### ISSUE THREAD

**Issue by UniQP** [rdmpage/maximum-weighted-bipartite-matching#5]
The documentations states:
If you are building from this repository you will need to do the standard things:

    aclocal
    autoconf
    automake
    ./configure
    make

If I run aclocal, I get the following warning:
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'

autoconf then runs without complaining, and automake throws the following errors:
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:6: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:9: error: required file './compile' not found
configure.in:9:   'automake --add-missing' can install 'compile'
configure.in:6: error: required file './install-sh' not found
configure.in:6:   'automake --add-missing' can install 'install-sh'
configure.in:6: error: required file './missing' not found
configure.in:6:   'automake --add-missing' can install 'missing'
Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Makefile.am: error: required file './INSTALL' not found
Makefile.am:   'automake --add-missing' can install 'INSTALL'
Makefile.am: error: required file './COPYING' not found
Makefile.am:   'automake --add-missing' can install 'COPYING'
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'

I used the following software versions:
aclocal (GNU automake) 1.14.1
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.14.1

**Comment by rdmpage** [comment]
Yes, the instructions are a bit skimpy. Until I have time to fix this, I simply go automake --add-missing to add the missing files. I've added a note about this to the README.
